"""Architecture configuration registry for Opasm.

Defines immutable architecture configurations for all supported CPU architectures
and provides lookup functions. This module is a leaf dependency with no internal
imports and no side effects on import (no engine initialization).

Public classes:
    ArchConfig - Frozen dataclass holding all configuration for a CPU architecture.

Public constants:
    ARCHITECTURES - Dict mapping architecture name strings to ArchConfig instances.

Public functions:
    get_architecture - Retrieve an ArchConfig by name.
    list_architectures - Return a sorted list of supported architecture names.
"""

from dataclasses import dataclass
from typing import Dict, List

from capstone import (
    CS_ARCH_ARM,
    CS_ARCH_ARM64,
    CS_ARCH_MIPS,
    CS_ARCH_PPC,
    CS_ARCH_X86,
    CS_MODE_32,
    CS_MODE_64,
    CS_MODE_ARM,
    CS_MODE_MIPS32,
    CS_MODE_MIPS64,
)
from keystone import (
    KS_ARCH_ARM,
    KS_ARCH_ARM64,
    KS_ARCH_MIPS,
    KS_ARCH_PPC,
    KS_ARCH_X86,
    KS_MODE_32,
    KS_MODE_64,
    KS_MODE_ARM,
    KS_MODE_LITTLE_ENDIAN,
    KS_MODE_MIPS32,
    KS_MODE_MIPS64,
    KS_MODE_PPC32,
    KS_MODE_PPC64,
)
from unicorn import (
    UC_ARCH_ARM,
    UC_ARCH_ARM64,
    UC_ARCH_MIPS,
    UC_ARCH_PPC,
    UC_ARCH_X86,
    UC_MODE_32,
    UC_MODE_64,
    UC_MODE_ARM,
    UC_MODE_MIPS32,
    UC_MODE_MIPS64,
    UC_MODE_PPC32,
    UC_MODE_PPC64,
)
from unicorn.arm64_const import (
    UC_ARM64_REG_NZCV,
    UC_ARM64_REG_PC,
    UC_ARM64_REG_SP,
    UC_ARM64_REG_X0,
    UC_ARM64_REG_X1,
    UC_ARM64_REG_X2,
    UC_ARM64_REG_X3,
    UC_ARM64_REG_X4,
    UC_ARM64_REG_X5,
    UC_ARM64_REG_X6,
    UC_ARM64_REG_X7,
    UC_ARM64_REG_X8,
    UC_ARM64_REG_X9,
    UC_ARM64_REG_X10,
    UC_ARM64_REG_X11,
    UC_ARM64_REG_X12,
    UC_ARM64_REG_X13,
    UC_ARM64_REG_X14,
    UC_ARM64_REG_X15,
    UC_ARM64_REG_X16,
    UC_ARM64_REG_X17,
    UC_ARM64_REG_X18,
    UC_ARM64_REG_X19,
    UC_ARM64_REG_X20,
    UC_ARM64_REG_X21,
    UC_ARM64_REG_X22,
    UC_ARM64_REG_X23,
    UC_ARM64_REG_X24,
    UC_ARM64_REG_X25,
    UC_ARM64_REG_X26,
    UC_ARM64_REG_X27,
    UC_ARM64_REG_X28,
    UC_ARM64_REG_X29,
    UC_ARM64_REG_X30,
)
from unicorn.arm_const import (
    UC_ARM_REG_CPSR,
    UC_ARM_REG_LR,
    UC_ARM_REG_PC,
    UC_ARM_REG_R0,
    UC_ARM_REG_R1,
    UC_ARM_REG_R2,
    UC_ARM_REG_R3,
    UC_ARM_REG_R4,
    UC_ARM_REG_R5,
    UC_ARM_REG_R6,
    UC_ARM_REG_R7,
    UC_ARM_REG_R8,
    UC_ARM_REG_R9,
    UC_ARM_REG_R10,
    UC_ARM_REG_R11,
    UC_ARM_REG_R12,
    UC_ARM_REG_SP,
)
from unicorn.mips_const import (
    UC_MIPS_REG_A0,
    UC_MIPS_REG_A1,
    UC_MIPS_REG_A2,
    UC_MIPS_REG_A3,
    UC_MIPS_REG_AT,
    UC_MIPS_REG_CP0_STATUS,
    UC_MIPS_REG_FP,
    UC_MIPS_REG_GP,
    UC_MIPS_REG_K0,
    UC_MIPS_REG_K1,
    UC_MIPS_REG_PC,
    UC_MIPS_REG_RA,
    UC_MIPS_REG_S0,
    UC_MIPS_REG_S1,
    UC_MIPS_REG_S2,
    UC_MIPS_REG_S3,
    UC_MIPS_REG_S4,
    UC_MIPS_REG_S5,
    UC_MIPS_REG_S6,
    UC_MIPS_REG_S7,
    UC_MIPS_REG_SP,
    UC_MIPS_REG_T0,
    UC_MIPS_REG_T1,
    UC_MIPS_REG_T2,
    UC_MIPS_REG_T3,
    UC_MIPS_REG_T4,
    UC_MIPS_REG_T5,
    UC_MIPS_REG_T6,
    UC_MIPS_REG_T7,
    UC_MIPS_REG_T8,
    UC_MIPS_REG_T9,
    UC_MIPS_REG_V0,
    UC_MIPS_REG_V1,
    UC_MIPS_REG_ZERO,
)
from unicorn.ppc_const import (
    UC_PPC_REG_0,
    UC_PPC_REG_1,
    UC_PPC_REG_2,
    UC_PPC_REG_3,
    UC_PPC_REG_4,
    UC_PPC_REG_5,
    UC_PPC_REG_6,
    UC_PPC_REG_7,
    UC_PPC_REG_8,
    UC_PPC_REG_9,
    UC_PPC_REG_10,
    UC_PPC_REG_11,
    UC_PPC_REG_12,
    UC_PPC_REG_13,
    UC_PPC_REG_14,
    UC_PPC_REG_15,
    UC_PPC_REG_16,
    UC_PPC_REG_17,
    UC_PPC_REG_18,
    UC_PPC_REG_19,
    UC_PPC_REG_20,
    UC_PPC_REG_21,
    UC_PPC_REG_22,
    UC_PPC_REG_23,
    UC_PPC_REG_24,
    UC_PPC_REG_25,
    UC_PPC_REG_26,
    UC_PPC_REG_27,
    UC_PPC_REG_28,
    UC_PPC_REG_29,
    UC_PPC_REG_30,
    UC_PPC_REG_31,
    UC_PPC_REG_CR,
    UC_PPC_REG_CTR,
    UC_PPC_REG_FPR0,
    UC_PPC_REG_FPR1,
    UC_PPC_REG_FPR2,
    UC_PPC_REG_FPR3,
    UC_PPC_REG_FPR4,
    UC_PPC_REG_FPR5,
    UC_PPC_REG_FPR6,
    UC_PPC_REG_FPR7,
    UC_PPC_REG_FPR8,
    UC_PPC_REG_FPR9,
    UC_PPC_REG_FPR10,
    UC_PPC_REG_FPR11,
    UC_PPC_REG_FPR12,
    UC_PPC_REG_FPR13,
    UC_PPC_REG_FPR14,
    UC_PPC_REG_FPR15,
    UC_PPC_REG_FPR16,
    UC_PPC_REG_FPR17,
    UC_PPC_REG_FPR18,
    UC_PPC_REG_FPR19,
    UC_PPC_REG_FPR20,
    UC_PPC_REG_FPR21,
    UC_PPC_REG_FPR22,
    UC_PPC_REG_FPR23,
    UC_PPC_REG_FPR24,
    UC_PPC_REG_FPR25,
    UC_PPC_REG_FPR26,
    UC_PPC_REG_FPR27,
    UC_PPC_REG_FPR28,
    UC_PPC_REG_FPR29,
    UC_PPC_REG_FPR30,
    UC_PPC_REG_FPR31,
    UC_PPC_REG_LR,
    UC_PPC_REG_PC,
    UC_PPC_REG_XER,
)
from unicorn.x86_const import (
    UC_X86_REG_AH,
    UC_X86_REG_AL,
    UC_X86_REG_AX,
    UC_X86_REG_BH,
    UC_X86_REG_BL,
    UC_X86_REG_BX,
    UC_X86_REG_CH,
    UC_X86_REG_CL,
    UC_X86_REG_CX,
    UC_X86_REG_DH,
    UC_X86_REG_DL,
    UC_X86_REG_DX,
    UC_X86_REG_EAX,
    UC_X86_REG_EBP,
    UC_X86_REG_EBX,
    UC_X86_REG_ECX,
    UC_X86_REG_EDI,
    UC_X86_REG_EDX,
    UC_X86_REG_EFLAGS,
    UC_X86_REG_EIP,
    UC_X86_REG_ESI,
    UC_X86_REG_ESP,
    UC_X86_REG_R8,
    UC_X86_REG_R9,
    UC_X86_REG_R10,
    UC_X86_REG_R11,
    UC_X86_REG_R12,
    UC_X86_REG_R13,
    UC_X86_REG_R14,
    UC_X86_REG_R15,
    UC_X86_REG_RAX,
    UC_X86_REG_RBP,
    UC_X86_REG_RBX,
    UC_X86_REG_RCX,
    UC_X86_REG_RDI,
    UC_X86_REG_RDX,
    UC_X86_REG_RIP,
    UC_X86_REG_RSI,
    UC_X86_REG_RSP,
)


@dataclass(frozen=True)
class ArchConfig:
    """Immutable configuration for a CPU architecture.

    Parameters:
        name: Architecture identifier (e.g., "x86", "arm64").
        uc_arch: Unicorn architecture constant.
        uc_mode: Unicorn mode constant.
        cs_arch: Capstone architecture constant.
        cs_mode: Capstone mode constant.
        ks_arch: Keystone architecture constant.
        ks_mode: Keystone mode constant.
        is_little_endian: True if the architecture uses little-endian byte order.
        registers: Mapping of register name strings to engine constant integers.
        instruction_pointer_register: Engine constant for the instruction pointer.
        stack_pointer_register: Engine constant for the stack pointer.
        stack_base: Base address for the stack memory region.
        code_base: Base address for the code memory region.
        data_base: Base address for the data memory region.
        word_size: Architecture word size in bytes (4 or 8).
    """

    name: str
    uc_arch: int
    uc_mode: int
    cs_arch: int
    cs_mode: int
    ks_arch: int
    ks_mode: int
    is_little_endian: bool
    registers: Dict[str, int]
    instruction_pointer_register: int
    stack_pointer_register: int
    stack_base: int
    code_base: int
    data_base: int
    word_size: int


# ---------------------------------------------------------------------------
# Shared base register maps for architecture families
# ---------------------------------------------------------------------------

_PPC_BASE_REGISTERS: Dict[str, int] = {
    "r0": UC_PPC_REG_0,
    "r1": UC_PPC_REG_1,
    "r2": UC_PPC_REG_2,
    "r3": UC_PPC_REG_3,
    "r4": UC_PPC_REG_4,
    "r5": UC_PPC_REG_5,
    "r6": UC_PPC_REG_6,
    "r7": UC_PPC_REG_7,
    "r8": UC_PPC_REG_8,
    "r9": UC_PPC_REG_9,
    "r10": UC_PPC_REG_10,
    "r11": UC_PPC_REG_11,
    "r12": UC_PPC_REG_12,
    "r13": UC_PPC_REG_13,
    "r14": UC_PPC_REG_14,
    "r15": UC_PPC_REG_15,
    "r16": UC_PPC_REG_16,
    "r17": UC_PPC_REG_17,
    "r18": UC_PPC_REG_18,
    "r19": UC_PPC_REG_19,
    "r20": UC_PPC_REG_20,
    "r21": UC_PPC_REG_21,
    "r22": UC_PPC_REG_22,
    "r23": UC_PPC_REG_23,
    "r24": UC_PPC_REG_24,
    "r25": UC_PPC_REG_25,
    "r26": UC_PPC_REG_26,
    "r27": UC_PPC_REG_27,
    "r28": UC_PPC_REG_28,
    "r29": UC_PPC_REG_29,
    "r30": UC_PPC_REG_30,
    "r31": UC_PPC_REG_31,
    "fpr0": UC_PPC_REG_FPR0,
    "fpr1": UC_PPC_REG_FPR1,
    "fpr2": UC_PPC_REG_FPR2,
    "fpr3": UC_PPC_REG_FPR3,
    "fpr4": UC_PPC_REG_FPR4,
    "fpr5": UC_PPC_REG_FPR5,
    "fpr6": UC_PPC_REG_FPR6,
    "fpr7": UC_PPC_REG_FPR7,
    "fpr8": UC_PPC_REG_FPR8,
    "fpr9": UC_PPC_REG_FPR9,
    "fpr10": UC_PPC_REG_FPR10,
    "fpr11": UC_PPC_REG_FPR11,
    "fpr12": UC_PPC_REG_FPR12,
    "fpr13": UC_PPC_REG_FPR13,
    "fpr14": UC_PPC_REG_FPR14,
    "fpr15": UC_PPC_REG_FPR15,
    "fpr16": UC_PPC_REG_FPR16,
    "fpr17": UC_PPC_REG_FPR17,
    "fpr18": UC_PPC_REG_FPR18,
    "fpr19": UC_PPC_REG_FPR19,
    "fpr20": UC_PPC_REG_FPR20,
    "fpr21": UC_PPC_REG_FPR21,
    "fpr22": UC_PPC_REG_FPR22,
    "fpr23": UC_PPC_REG_FPR23,
    "fpr24": UC_PPC_REG_FPR24,
    "fpr25": UC_PPC_REG_FPR25,
    "fpr26": UC_PPC_REG_FPR26,
    "fpr27": UC_PPC_REG_FPR27,
    "fpr28": UC_PPC_REG_FPR28,
    "fpr29": UC_PPC_REG_FPR29,
    "fpr30": UC_PPC_REG_FPR30,
    "fpr31": UC_PPC_REG_FPR31,
    "pc": UC_PPC_REG_PC,
    "lr": UC_PPC_REG_LR,
    "ctr": UC_PPC_REG_CTR,
    "xer": UC_PPC_REG_XER,
    "cr": UC_PPC_REG_CR,
}
"""Shared register-name-to-constant mapping for PPC32 and PPC64 architectures."""

_MIPS_BASE_REGISTERS: Dict[str, int] = {
    "CP0_STATUS": UC_MIPS_REG_CP0_STATUS,
    "r0 (zero)": UC_MIPS_REG_ZERO,
    "r1 (at)": UC_MIPS_REG_AT,
    "r2 (v0)": UC_MIPS_REG_V0,
    "r3 (v1)": UC_MIPS_REG_V1,
    "r4 (a0)": UC_MIPS_REG_A0,
    "r5 (a1)": UC_MIPS_REG_A1,
    "r6 (a2)": UC_MIPS_REG_A2,
    "r7 (a3)": UC_MIPS_REG_A3,
    "r8 (t0)": UC_MIPS_REG_T0,
    "r9 (t1)": UC_MIPS_REG_T1,
    "r10 (t2)": UC_MIPS_REG_T2,
    "r11 (t3)": UC_MIPS_REG_T3,
    "r12 (t4)": UC_MIPS_REG_T4,
    "r13 (t5)": UC_MIPS_REG_T5,
    "r14 (t6)": UC_MIPS_REG_T6,
    "r15 (t7)": UC_MIPS_REG_T7,
    "r16 (s0)": UC_MIPS_REG_S0,
    "r17 (s1)": UC_MIPS_REG_S1,
    "r18 (s2)": UC_MIPS_REG_S2,
    "r19 (s3)": UC_MIPS_REG_S3,
    "r20 (s4)": UC_MIPS_REG_S4,
    "r21 (s5)": UC_MIPS_REG_S5,
    "r22 (s6)": UC_MIPS_REG_S6,
    "r23 (s7)": UC_MIPS_REG_S7,
    "r24 (t8)": UC_MIPS_REG_T8,
    "r25 (t9)": UC_MIPS_REG_T9,
    "r26 (k0)": UC_MIPS_REG_K0,
    "r27 (k1)": UC_MIPS_REG_K1,
    "r28 (gp)": UC_MIPS_REG_GP,
    "r29 (sp)": UC_MIPS_REG_SP,
    "r30 (fp)": UC_MIPS_REG_FP,
    "r31 (ra)": UC_MIPS_REG_RA,
    "pc": UC_MIPS_REG_PC,
    "sp": UC_MIPS_REG_SP,
}
"""Shared register-name-to-constant mapping for MIPS32 and MIPS64 architectures."""


# ---------------------------------------------------------------------------
# Architecture configurations
# ---------------------------------------------------------------------------

ARCHITECTURES: Dict[str, ArchConfig] = {
    "x86": ArchConfig(
        name="x86",
        uc_arch=UC_ARCH_X86,
        uc_mode=UC_MODE_32,
        cs_arch=CS_ARCH_X86,
        cs_mode=CS_MODE_32,
        ks_arch=KS_ARCH_X86,
        ks_mode=KS_MODE_32,
        is_little_endian=True,
        registers={
            "eax": UC_X86_REG_EAX,
            "ebx": UC_X86_REG_EBX,
            "ecx": UC_X86_REG_ECX,
            "edx": UC_X86_REG_EDX,
            "esi": UC_X86_REG_ESI,
            "edi": UC_X86_REG_EDI,
            "esp": UC_X86_REG_ESP,
            "ebp": UC_X86_REG_EBP,
            "eip": UC_X86_REG_EIP,
            "eflags": UC_X86_REG_EFLAGS,
            "ax": UC_X86_REG_AX,
            "bx": UC_X86_REG_BX,
            "cx": UC_X86_REG_CX,
            "dx": UC_X86_REG_DX,
            "al": UC_X86_REG_AL,
            "bl": UC_X86_REG_BL,
            "cl": UC_X86_REG_CL,
            "dl": UC_X86_REG_DL,
            "ah": UC_X86_REG_AH,
            "bh": UC_X86_REG_BH,
            "ch": UC_X86_REG_CH,
            "dh": UC_X86_REG_DH,
        },
        instruction_pointer_register=UC_X86_REG_EIP,
        stack_pointer_register=UC_X86_REG_ESP,
        stack_base=0x7FFF0000,
        code_base=0x400000,
        data_base=0x10000000,
        word_size=4,
    ),
    "x64": ArchConfig(
        name="x64",
        uc_arch=UC_ARCH_X86,
        uc_mode=UC_MODE_64,
        cs_arch=CS_ARCH_X86,
        cs_mode=CS_MODE_64,
        ks_arch=KS_ARCH_X86,
        ks_mode=KS_MODE_64,
        is_little_endian=True,
        registers={
            "rax": UC_X86_REG_RAX,
            "rbx": UC_X86_REG_RBX,
            "rcx": UC_X86_REG_RCX,
            "rdx": UC_X86_REG_RDX,
            "rsi": UC_X86_REG_RSI,
            "rdi": UC_X86_REG_RDI,
            "rsp": UC_X86_REG_RSP,
            "rbp": UC_X86_REG_RBP,
            "rip": UC_X86_REG_RIP,
            "rflags": UC_X86_REG_EFLAGS,
            "r8": UC_X86_REG_R8,
            "r9": UC_X86_REG_R9,
            "r10": UC_X86_REG_R10,
            "r11": UC_X86_REG_R11,
            "r12": UC_X86_REG_R12,
            "r13": UC_X86_REG_R13,
            "r14": UC_X86_REG_R14,
            "r15": UC_X86_REG_R15,
            "eax": UC_X86_REG_EAX,
            "ebx": UC_X86_REG_EBX,
            "ecx": UC_X86_REG_ECX,
            "edx": UC_X86_REG_EDX,
        },
        instruction_pointer_register=UC_X86_REG_RIP,
        stack_pointer_register=UC_X86_REG_RSP,
        stack_base=0x7FFF00000000,
        code_base=0x400000,
        data_base=0x10000000,
        word_size=8,
    ),
    "arm": ArchConfig(
        name="arm",
        uc_arch=UC_ARCH_ARM,
        uc_mode=UC_MODE_ARM,
        cs_arch=CS_ARCH_ARM,
        cs_mode=CS_MODE_ARM,
        ks_arch=KS_ARCH_ARM,
        ks_mode=KS_MODE_ARM,
        is_little_endian=True,
        registers={
            "r0": UC_ARM_REG_R0,
            "r1": UC_ARM_REG_R1,
            "r2": UC_ARM_REG_R2,
            "r3": UC_ARM_REG_R3,
            "r4": UC_ARM_REG_R4,
            "r5": UC_ARM_REG_R5,
            "r6": UC_ARM_REG_R6,
            "r7": UC_ARM_REG_R7,
            "r8": UC_ARM_REG_R8,
            "r9": UC_ARM_REG_R9,
            "r10": UC_ARM_REG_R10,
            "r11": UC_ARM_REG_R11,
            "r12": UC_ARM_REG_R12,
            "sp": UC_ARM_REG_SP,
            "lr": UC_ARM_REG_LR,
            "pc": UC_ARM_REG_PC,
            "cpsr": UC_ARM_REG_CPSR,
        },
        instruction_pointer_register=UC_ARM_REG_PC,
        stack_pointer_register=UC_ARM_REG_SP,
        stack_base=0x7FFF0000,
        code_base=0x10000,
        data_base=0x20000000,
        word_size=4,
    ),
    "arm64": ArchConfig(
        name="arm64",
        uc_arch=UC_ARCH_ARM64,
        uc_mode=UC_MODE_ARM,
        cs_arch=CS_ARCH_ARM64,
        cs_mode=CS_MODE_ARM,
        ks_arch=KS_ARCH_ARM64,
        ks_mode=KS_MODE_LITTLE_ENDIAN,
        is_little_endian=True,
        registers={
            "x0": UC_ARM64_REG_X0,
            "x1": UC_ARM64_REG_X1,
            "x2": UC_ARM64_REG_X2,
            "x3": UC_ARM64_REG_X3,
            "x4": UC_ARM64_REG_X4,
            "x5": UC_ARM64_REG_X5,
            "x6": UC_ARM64_REG_X6,
            "x7": UC_ARM64_REG_X7,
            "x8": UC_ARM64_REG_X8,
            "x9": UC_ARM64_REG_X9,
            "x10": UC_ARM64_REG_X10,
            "x11": UC_ARM64_REG_X11,
            "x12": UC_ARM64_REG_X12,
            "x13": UC_ARM64_REG_X13,
            "x14": UC_ARM64_REG_X14,
            "x15": UC_ARM64_REG_X15,
            "x16": UC_ARM64_REG_X16,
            "x17": UC_ARM64_REG_X17,
            "x18": UC_ARM64_REG_X18,
            "x19": UC_ARM64_REG_X19,
            "x20": UC_ARM64_REG_X20,
            "x21": UC_ARM64_REG_X21,
            "x22": UC_ARM64_REG_X22,
            "x23": UC_ARM64_REG_X23,
            "x24": UC_ARM64_REG_X24,
            "x25": UC_ARM64_REG_X25,
            "x26": UC_ARM64_REG_X26,
            "x27": UC_ARM64_REG_X27,
            "x28": UC_ARM64_REG_X28,
            "x29": UC_ARM64_REG_X29,
            "x30": UC_ARM64_REG_X30,
            "sp": UC_ARM64_REG_SP,
            "pc": UC_ARM64_REG_PC,
            "nzcv": UC_ARM64_REG_NZCV,
        },
        instruction_pointer_register=UC_ARM64_REG_PC,
        stack_pointer_register=UC_ARM64_REG_SP,
        stack_base=0x7FFF00000000,
        code_base=0x400000,
        data_base=0x10000000,
        word_size=8,
    ),
    "mips32": ArchConfig(
        name="mips32",
        uc_arch=UC_ARCH_MIPS,
        uc_mode=UC_MODE_MIPS32,
        cs_arch=CS_ARCH_MIPS,
        cs_mode=CS_MODE_MIPS32,
        ks_arch=KS_ARCH_MIPS,
        ks_mode=KS_MODE_MIPS32,
        is_little_endian=False,
        registers=_MIPS_BASE_REGISTERS,
        instruction_pointer_register=UC_MIPS_REG_PC,
        stack_pointer_register=UC_MIPS_REG_SP,
        stack_base=0x7FFF0000,
        code_base=0x400000,
        data_base=0x10000000,
        word_size=4,
    ),
    "mips64": ArchConfig(
        name="mips64",
        uc_arch=UC_ARCH_MIPS,
        uc_mode=UC_MODE_MIPS64,
        cs_arch=CS_ARCH_MIPS,
        cs_mode=CS_MODE_MIPS64,
        ks_arch=KS_ARCH_MIPS,
        ks_mode=KS_MODE_MIPS64,
        is_little_endian=False,
        registers=_MIPS_BASE_REGISTERS,
        instruction_pointer_register=UC_MIPS_REG_PC,
        stack_pointer_register=UC_MIPS_REG_SP,
        stack_base=0x7FFF00000000,
        code_base=0x400000,
        data_base=0x10000000,
        word_size=8,
    ),
    "ppc32": ArchConfig(
        name="ppc32",
        uc_arch=UC_ARCH_PPC,
        uc_mode=UC_MODE_PPC32,
        cs_arch=CS_ARCH_PPC,
        cs_mode=CS_MODE_32,
        ks_arch=KS_ARCH_PPC,
        ks_mode=KS_MODE_PPC32,
        is_little_endian=False,
        registers=_PPC_BASE_REGISTERS,
        instruction_pointer_register=UC_PPC_REG_PC,
        stack_pointer_register=UC_PPC_REG_1,
        stack_base=0x7FFF0000,
        code_base=0x10000000,
        data_base=0x20000000,
        word_size=4,
    ),
    "ppc64": ArchConfig(
        name="ppc64",
        uc_arch=UC_ARCH_PPC,
        uc_mode=UC_MODE_PPC64,
        cs_arch=CS_ARCH_PPC,
        cs_mode=CS_MODE_64,
        ks_arch=KS_ARCH_PPC,
        ks_mode=KS_MODE_PPC64,
        is_little_endian=False,
        registers=_PPC_BASE_REGISTERS,
        instruction_pointer_register=UC_PPC_REG_PC,
        stack_pointer_register=UC_PPC_REG_1,
        stack_base=0x7FFF00000000,
        code_base=0x10000000,
        data_base=0x20000000,
        word_size=8,
    ),
}
"""Dict mapping architecture name strings to their ArchConfig instances."""


def get_architecture(name: str) -> ArchConfig:
    """Retrieve an ArchConfig by architecture name.

    Parameters:
        name: Architecture identifier (e.g., "x86", "arm64", "ppc32").

    Returns:
        The ArchConfig for the requested architecture.

    Raises:
        KeyError: If the architecture name is not in the registry.
    """
    return ARCHITECTURES[name]


def list_architectures() -> List[str]:
    """Return a sorted list of all supported architecture names.

    Returns:
        Sorted list of architecture name strings.
    """
    return sorted(ARCHITECTURES.keys())
